Add Vectorlike
rubatopy/rubato pull request #321
Opened 2022-08-24 20:46 UTC by tinmarr

Allows for vectorlikes

Closes #166

2022-08-24 20:58 UTC, mrElnekave commented on rubato/c_src/c_draw.py
> +        x, y = (int(v[0]), int(v[1]))
get rid of parentheses

2022-08-24 21:17 UTC, mrElnekave commented on rubato/struct/gameobject/sprites/animation.py
> +        to_x, to_y = (int(to_coord[0]), int(to_coord[1]))
.

2022-08-24 21:26 UTC, mrElnekave approved these changes
looks good.

2022-08-24 23:04 UTC, tsedan requested changes
offset_demo is currently broken. will rereview once @tinmarr fixes

2022-08-25 02:34 UTC, tsedan approved these changes
Looks good!!! :)

2022-08-25 02:34 UTC, merged