text update
rubatopy/rubato pull request #438
Opened 2022-12-07 06:38 UTC by mrElnekave

# Description

#409

2022-12-07 06:44 UTC, tinmarr commented on rubato/structure/gameobject/ui/text.py
> +    Any change to the characters of the text need to be done directly to the font object.
delete line 13

2022-12-08 01:28 UTC, mrElnekave reviewed
Ready for review, looks good

2022-12-08 01:37 UTC, tinmarr requested changes

2022-12-08 01:37 UTC, tinmarr commented on CHANGELOG.md
> +-   Font styles are integers you | together.
```suggestion
-   `font.add_style` and `font.remove_style` no longer look if the thing you are removing or adding exists.
-   `Font` styles are integers you | together.
```

2022-12-08 01:37 UTC, tinmarr commented on CHANGELOG.md
> +-   Text no longer can affect Fonts directly.
```suggestion
-   `Text` no longer can affect `Font`s directly.
```

2022-12-08 01:37 UTC, tinmarr commented on demo/test/text.py
> +import rubato as rb
Please delete this file. We don't want a test folder in the demo folder anymore

2022-12-08 01:37 UTC, tinmarr commented on rubato/utils/rendering/font.py
> +        styles: The styles to apply to the font. Defaults to 0. You can add multiple styles by | them together.
```suggestion
        styles: The styles to apply to the font. Set multiple styles by adding them together. Defaults to 0.
```

2022-12-08 01:37 UTC, tinmarr commented on rubato/utils/rendering/font.py
> +            Can be one of the following: Font.BOLD, Font.ITALIC, Font.UNDERLINE, Font.STRIKETHROUGH.
Move line 125 to the function description (inline with line 121)

2022-12-08 01:37 UTC, tinmarr commented on rubato/utils/rendering/font.py
> +            Can be one of the following: Font.BOLD, Font.ITALIC, Font.UNDERLINE, Font.STRIKETHROUGH.
Same as previous comment

2022-12-08 01:52 UTC, tinmarr approved these changes

2022-12-08 01:56 UTC, merged